yf_bin: update i686 target utilities to current versions

diff --git a/target/i686/sign_image b/target/i686/sign_image
--- a/target/i686/sign_image
+++ b/target/i686/sign_image
@@ -1,4 +1,5 @@
 #! /bin/sh
+# SPDX-License-Identifier: GPL-2.0-or-later
 ####################################################################################
 #                                                                                  #
 # sign a tar archive with our private RSA key                                      #
@@ -36,6 +37,45 @@ box_key_name="/var/flash/websrv_ssl_key"
 source "$my_path/image_signing_files.inc"
 ####################################################################################
 #                                                                                  #
+# get the path for needed external commands, if called in any toolchain            #
+#                                                                                  #
+# looks a little bit complicated, but has to support definitions for BusyBox       #
+# applets as commands to be used and simple quoting isn't enough to ensure proper  #
+# substitution, but spreading 'eval' statements all over the code looks ugly, too  #
+#                                                                                  #
+####################################################################################
+if ! [ -z "$YF_SIGNIMAGE_TAR" ]; then
+	__YF_SIGNIMAGE_TAR="$YF_SIGNIMAGE_TAR"
+	__yf_signimage_tar()
+	{
+		eval $__YF_SIGNIMAGE_TAR $*
+	}
+	YF_SIGNIMAGE_TAR="__yf_signimage_tar"
+else
+	YF_SIGNIMAGE_TAR="tar"
+fi
+if ! [ -z "$YF_SIGNIMAGE_DD" ]; then
+	__YF_SIGNIMAGE_DD="$YF_SIGNIMAGE_DD"
+	__yf_signimage_dd()
+	{
+		eval $__YF_SIGNIMAGE_DD $*
+	}
+	YF_SIGNIMAGE_DD="__yf_signimage_dd"
+else
+	YF_SIGNIMAGE_DD="dd"
+fi
+if ! [ -z "$YF_SIGNIMAGE_OPENSSL" ]; then
+	__YF_SIGNIMAGE_OPENSSL="$YF_SIGNIMAGE_OPENSSL"
+	__yf_signimage_openssl()
+	{
+		eval $__YF_SIGNIMAGE_OPENSSL $*
+	}
+	YF_SIGNIMAGE_OPENSSL="__yf_signimage_openssl"
+else
+	YF_SIGNIMAGE_OPENSSL="openssl"
+fi
+####################################################################################
+#                                                                                  #
 # some subfunctions                                                                #
 #                                                                                  #
 ####################################################################################
@@ -44,9 +84,9 @@ show_ok() { echo -e "\x1B[1;32mOK\x1B[0m" 1>&2; }
 show_version() 
 { 
 	local v
-	v=$(openssl version 2>/dev/null)
+	v=$("$YF_SIGNIMAGE_OPENSSL" version 2>/dev/null)
 	if [ $? -eq 127 ]; then
-		echo -e "Missing \x1B[1mopenssl\x1B[0m binary." 1>&2
+		echo -e "Missing \x1B[1mopenssl\x1B[0m binary, set YF_SIGNIMAGE_OPENSSL variable to its path name." 1>&2
 		return 1
 	else
 		echo -e "Found \x1B[1;34m$v\x1B[0m" 1>&2
@@ -87,6 +127,23 @@ y\nthe signed file with AVM components."
 }
 ####################################################################################
 #                                                                                  #
+# compute checksum of a TAR header                                                 #
+#                                                                                  #
+####################################################################################
+checksum()
+{
+	read_values()
+	{
+		while read pos left right; do
+			sum=$(( sum + 0$left ))
+		done
+		printf "%d" $sum
+	}
+	sum=0
+	cmp -l -- "$1" /dev/zero 2>/dev/null | read_values
+}
+####################################################################################
+#                                                                                  #
 # try to identify FRITZ!OS as runtime environment (not too sophisticated, but it   #
 # should be able to make this distinction)                                         #
 #                                                                                  #
@@ -111,7 +168,7 @@ is_fritzos_environment()
 # check parameters                                                                 #
 #                                                                                  #
 ####################################################################################
-if [ -z $1 ]; then
+if [ -z "$1" ]; then
 		usage 1>&2
 		exit 1
 else
@@ -133,7 +190,7 @@ fi
 show_version
 [ $? -ne 0 ] && exit 1
 echo -en "Check \x1B[1mdgst\x1B[0m command ... " 1>&2
-echo "" | openssl dgst 2>&1 | grep -q '^(stdin)=' 2>/dev/null 1>&2
+echo "" | "$YF_SIGNIMAGE_OPENSSL" dgst 2>&1 | grep -q '^(stdin)=' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
 	show_ok 
@@ -142,7 +199,7 @@ else
 	exit 1
 fi
 echo -en "Check \x1B[1mrsa\x1B[0m command ... " 1>&2
-echo "" | openssl rsa 2>&1 | grep -q '^unable to load' 2>/dev/null 1>&2
+echo "" | "$YF_SIGNIMAGE_OPENSSL" rsa 2>&1 | grep -q '^unable to load' 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
 	show_ok 
@@ -173,7 +230,7 @@ else
 	hash_algo="md5"
 fi
 echo -en "Verify hash algorithm \x1B[1m$hash_algo\x1B[0m is supported ... " 1>&2
-echo "" | openssl dgst -$hash_algo 2>&1 2>/dev/null 1>&2
+echo "" | "$YF_SIGNIMAGE_OPENSSL" dgst -$hash_algo 2>&1 2>/dev/null 1>&2
 rc=$?
 if [ $rc -eq 0 ]; then
 	show_ok 
@@ -183,15 +240,25 @@ else
 fi
 ####################################################################################
 #                                                                                  #
+# use 'force-local' option with GNU TAR, if the image name contains a colon        #
+#                                                                                  #
+####################################################################################
+if [ -n "$(expr "$image_file" : ".*\(:\).*")" ]; then
+	"$YF_SIGNIMAGE_TAR" --help 2>&1 | grep -q 'force-local' 2>/dev/null && force_local="--force-local"
+else
+	force_local=""
+fi
+####################################################################################
+#                                                                                  #
 # verify input file format                                                         #
 #                                                                                  #
 ####################################################################################
-dd if="$image_file" bs=1 skip=257 count=5 status=none 2>/dev/null | grep -q "^ustar\$" 2>/dev/null
+"$YF_SIGNIMAGE_DD" if="$image_file" bs=1 skip=257 count=5 status=none 2>/dev/null | grep -q "^ustar\$" 2>/dev/null
 if [ $? -ne 0 ]; then
 	echo -e "Input file doesn't look like a TAR archive." 1>&2
 	exit 1
 fi
-dd if="$image_file" bs=100 count=1 status=none 2>/dev/null | grep -q "PaxHeaders" 2>/dev/null
+"$YF_SIGNIMAGE_DD" if="$image_file" bs=100 count=1 status=none 2>/dev/null | grep -q "PaxHeaders" 2>/dev/null
 if [ $? -eq 0 ]; then
 	echo -e "Input file contains extended headers (PaxHeaders) and may not be signed this way." 1>&2
 	exit 1
@@ -210,7 +277,7 @@ trap "rm -r \"$tmp\"" EXIT HUP
 #                                                                                  #
 ####################################################################################
 offset=0
-tar -t -v -f "$image_file" |
+"$YF_SIGNIMAGE_TAR" -t -v -f "$image_file" $force_local |
 sed -n -e "s|^[^ ]* *[^ ]* *\([0-9]*\) *[^ ]* *[^ ]* *\(.*\)\$|SIZE=\1 MEMBER=\2|p" |
 while read line; do
 	eval $line
@@ -293,7 +360,7 @@ fi
 ####################################################################################
 if [ $on_box -eq 0 ]; then
 	echo -en "Check the password for the private key file ... " 1>&2
-	openssl rsa -in "${name_prefix}.${private_extension}" -noout -passin "pass:$KEYPASSWORD" 2>/dev/null 1>&2
+	"$YF_SIGNIMAGE_OPENSSL" rsa -in "${name_prefix}.${private_extension}" -noout -passin "pass:$KEYPASSWORD" 2>/dev/null 1>&2
 	rc=$?
 	if [ $rc -eq 0 ]; then
 		show_ok 
@@ -304,18 +371,23 @@ if [ $on_box -eq 0 ]; then
 fi
 ####################################################################################
 #                                                                                  #
-# prepare a temporary directory and cleanup on exit                                #
-#                                                                                  #
-####################################################################################
-tmp=$(mktemp -d)
-[ $? -eq 127 ] && tmp="/tmp/tmp.$(date +%s).$$" && mkdir -p "$tmp"
-trap "rm -r \"$tmp\"" EXIT HUP
-####################################################################################
-#                                                                                  #
 # create a subdirectory 'var' to prepare a TAR file of our signature later         #
 #                                                                                  #
 ####################################################################################
 mkdir -p "$tmp/var"
+####################################################################################
+#                                                                                  #
+# prepare a temporary block as filler, if circumvention of AVM's hash error is     #
+# needed                                                                           #
+#                                                                                  #
+####################################################################################
+if [ $(( ( copy_blocks + 2 ) % 20 )) -eq 0 ]; then
+	echo -ne "Repeating first entry as filler ... " 1>&2
+	"$YF_SIGNIMAGE_DD" if="$image_file" of="$tmp/filler.bin" bs=512 count=1 status=none 2>/dev/null
+	show_ok
+else
+	touch "$tmp/filler.bin"
+fi
 ####################################################################################
 #                                                                                  #
 # prepare a temporary block for an empty TAR member - 512 byte header and 512 byte #
@@ -323,7 +395,7 @@ mkdir -p "$tmp/var"
 # blocks with a size of 512 octets)                                                #
 #                                                                                  #
 ####################################################################################
-dd if=/dev/zero of="$tmp/1K.bin" bs=512 count=2 status=none 2>/dev/null
+"$YF_SIGNIMAGE_DD" if=/dev/zero of="$tmp/1K.bin" bs=512 count=2 status=none 2>/dev/null
 ####################################################################################
 #                                                                                  #
 # generate the signature file                                                      #
@@ -335,11 +407,12 @@ dd if=/dev/zero of="$tmp/1K.bin" bs=512 count=2 status=none 2>/dev/null
 #                                                                                  #
 ##################################A#################################################
 echo -en "Signing the image hash (\x1B[1m$hash_algo\x1B[0m) with RSA key from \x1B[1m${name_prefix}.${private_extension}\x1B[0m ... " 1>&2
-dd if="$image_file" bs=512 count=$copy_blocks status=none 2>&1 | cat - "$tmp/1K.bin" "$tmp/1K.bin" | 
-openssl dgst -$hash_algo -sign "${name_prefix}.${private_extension}" -out "$tmp/var/signature" -passin "pass:$KEYPASSWORD"
+"$YF_SIGNIMAGE_DD" if="$image_file" bs=512 count=$copy_blocks status=none 2>&1 | cat - "$tmp/filler.bin" "$tmp/1K.bin" "$tmp/1K.bin" |
+"$YF_SIGNIMAGE_OPENSSL" dgst -$hash_algo -sign "${name_prefix}.${private_extension}" -out "$tmp/var/signature" -passin "pass:$KEYPASSWORD"
 rc=$?
 if [ $rc -eq 0 ]; then
-	show_ok 
+	show_ok
+	sigsize=$(stat -c %s "$tmp/var/signature")
 else
 	show_error
 	exit 1
@@ -350,14 +423,28 @@ fi
 #                                                                                  #
 ####################################################################################
 echo -en "Copying resulting image to output ... " 1>&2
-dd if="$image_file" bs=512 count=$copy_blocks status=none
+"$YF_SIGNIMAGE_DD" if="$image_file" bs=512 count=$copy_blocks status=none
+cat "$tmp/filler.bin"
 ####################################################################################
 #                                                                                  #
-# and append another TAR archive containing only our newly created signature file  #
+# build our own signature member using the first member entry from image           #
 #                                                                                  #
 ####################################################################################
-tar --version 2>/dev/null | grep -q GNU 2>/dev/null && format=" --format=gnu" || format=""
-tar $format -C "$tmp" -O -c ./var/signature | dd bs=512 count=4 status=none 2>/dev/null
+"$YF_SIGNIMAGE_DD" if="$image_file" of="$tmp/header" bs=512 count=1 status=none 2>/dev/null
+printf "signature" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=6 conv=notrunc status=none 2>/dev/null
+printf "%04o\000" $sigsize | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=131 conv=notrunc status=none 2>/dev/null
+printf "0" | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=156 conv=notrunc status=none 2>/dev/null
+printf "        " | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=148 conv=notrunc status=none 2>/dev/null
+chksum=$(checksum "$tmp/header")
+printf "%06o\000" $chksum  | "$YF_SIGNIMAGE_DD" of="$tmp/header" bs=1 seek=148 conv=notrunc status=none 2>/dev/null
+####################################################################################
+#                                                                                  #
+# and append signature content and EoA blocks                                      #
+#                                                                                  #
+####################################################################################
+cat "$tmp/header" "$tmp/var/signature"
+"$YF_SIGNIMAGE_DD" if=/dev/zero bs=$(( 512 - sigsize )) count=1 status=none 2>/dev/null
+cat "$tmp/1K.bin"
 show_ok
 ####################################################################################
 #                                                                                  #
